apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: w9-success-rate
  namespace: w9-demo
spec:
  metrics:
    - name: success-rate
      interval: 30s
      count: 3
      failureLimit: 1
      successCondition: result[0] >= 0.95
      provider:
        prometheus:
          address: http://prometheus-server.monitoring.svc.cluster.local
          query: |
            sum(rate(http_requests_total{status!~"5.."}[5m]))
            /
            sum(rate(http_requests_total[5m]))
