apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: w9-demo
data:
  collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      prometheus:
        config:
          scrape_configs:
            - job_name: w9-demo-app
              scrape_interval: 15s
              static_configs:
                - targets:
                    - w9-demo-app.w9-demo.svc.cluster.local:80

    exporters:
      logging:
        verbosity: detailed

    service:
      pipelines:
        metrics:
          receivers:
            - otlp
            - prometheus
          exporters:
            - logging
        logs:
          receivers:
            - otlp
          exporters:
            - logging
        traces:
          receivers:
            - otlp
          exporters:
            - logging
