apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: apps-prod
spec:
  provider:
    aws:
      # AWS Secrets Manager là backend lưu secret production.
      service: SecretsManager
      # Region cần khớp nơi secret thật được tạo.
      region: ap-southeast-1
      auth:
        jwt:
          serviceAccountRef:
            # ServiceAccount này nên được gắn IAM Role for Service Accounts trong EKS.
            name: external-secrets
            namespace: external-secrets

